# Generated by Django 4.2.29 on 2026-03-27 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=255)),
                ('sender_domain', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('phishing', 'Phishing'), ('suspicious', 'Suspicious'), ('safe', 'Safe'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('text_score', models.FloatField(default=0.0)),
                ('url_score', models.FloatField(default=0.0)),
                ('metadata_score', models.FloatField(default=0.0)),
                ('attachment_score', models.FloatField(default=0.0)),
                ('extracted_urls', models.JSONField(default=list)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('why_flagged', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('level', models.CharField(default='info', max_length=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='detector.email')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
